// <auto-generated />
using System;
using F5Clothes_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F5Clothes_DAL.Migrations
{
    [DbContext(typeof(DbduAnTnContext))]
    [Migration("20241102085722_CreateDb1")]
    partial class CreateDb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F5Clothes_DAL.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenChatLieu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatLieu", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.ChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoaiChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.DiaChi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKH");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKh");

                    b.ToTable("DiaChi", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GiamGium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("GiaTriGiam")
                        .HasColumnType("bigint");

                    b.Property<int?>("HinhThucGiam")
                        .HasColumnType("int");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("TenGiamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GiamGia");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKH");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKh");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("DonGiaKhiGiam")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("IdGh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdGH");

                    b.Property<Guid?>("IdSpct")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSPCT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGh");

                    b.HasIndex("IdSpct");

                    b.ToTable("GioHangChiTiet", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HinhThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("HinhThucThanhToan1")
                        .HasColumnType("int")
                        .HasColumnName("HinhThucThanhToan");

                    b.Property<Guid?>("IdHd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdHD");

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKH");

                    b.Property<Guid?>("IdNv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNV");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SoTienTra")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHd");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdNv");

                    b.ToTable("HinhThucThanhToan", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChiNhanHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaTriGiam")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKH");

                    b.Property<Guid?>("IdNv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNV");

                    b.Property<Guid?>("IdVouCher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LoaiHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayChoGiaoHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayHuy")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayNhanHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime");

                    b.Property<string>("SdtnguoiGiao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SDTNguoiGiao");

                    b.Property<string>("SdtnguoiNhan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SDTNguoiNhan");

                    b.Property<string>("TenNguoiGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("TienGiaoHang")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("TienKhachTra")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("TienThua")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdNv");

                    b.HasIndex("IdVouCher");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("DonGiaKhiGiam")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("IdHd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdHD");

                    b.Property<Guid?>("IdSpct")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSPCT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHd");

                    b.HasIndex("IdSpct");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdSp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSP");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSp");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTenKh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HoVaTenKH");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdHd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdHD");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiThaoTac")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LichSuHo__3214EC07D30E6227");

                    b.HasIndex("IdHd");

                    b.ToTable("LichSuHoaDon", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenMauSac")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTenNv")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HoVaTenNV");

                    b.Property<int?>("IdCv")
                        .HasColumnType("int")
                        .HasColumnName("IdCV");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCv");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.RefeshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKH");

                    b.Property<Guid?>("IdNv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNV");

                    b.Property<DateTime?>("ThoiGianHetHan")
                        .HasColumnType("datetime");

                    b.Property<string>("ToKen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdNv");

                    b.ToTable("RefeshToken", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("DonGiaKhiGiam")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<Guid?>("IdCl")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCL");

                    b.Property<Guid?>("IdDm")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdDM");

                    b.Property<Guid?>("IdGg")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdGG");

                    b.Property<Guid?>("IdTh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTH");

                    b.Property<Guid?>("IdXx")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdXX");

                    b.Property<string>("ImageDefaul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayThem")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThemGiamGia")
                        .HasColumnType("datetime");

                    b.Property<string>("TenSp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TenSP");

                    b.Property<int?>("TheLoai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCl");

                    b.HasIndex("IdDm");

                    b.HasIndex("IdGg");

                    b.HasIndex("IdTh");

                    b.HasIndex("IdXx");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdMs")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdMS");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSP");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMs");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdSp");

                    b.ToTable("SanPhamChiTiet", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenSize")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Size", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.ThuongHieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenThuongHieu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.VouCher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long?>("DieuKienToiThieuHoaDon")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("GiaTriGiam")
                        .HasColumnType("bigint");

                    b.Property<int?>("HinhThucGiam")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiVouCher")
                        .HasColumnType("int");

                    b.Property<string>("MaVouCher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuongDung")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMa")
                        .HasColumnType("int");

                    b.Property<string>("TenVouCher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VouCher", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.XuatXu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenXuatXu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("XuatXu", (string)null);
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.DiaChi", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.KhachHang", "IdKhNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdKh")
                        .HasConstraintName("FK_DiaChi_KhachHang");

                    b.Navigation("IdKhNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GioHang", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.KhachHang", "IdKhNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("IdKh")
                        .HasConstraintName("FK_GioHang_KhachHang");

                    b.Navigation("IdKhNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.GioHang", "IdGhNavigation")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGh")
                        .HasConstraintName("FK_GioHangChiTiet_GioHang");

                    b.HasOne("F5Clothes_DAL.Models.SanPhamChiTiet", "IdSpctNavigation")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSpct")
                        .HasConstraintName("FK_GioHangChiTiet_SanPhamChiTiet");

                    b.Navigation("IdGhNavigation");

                    b.Navigation("IdSpctNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HinhThucThanhToan", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.HoaDon", "IdHdNavigation")
                        .WithMany("HinhThucThanhToans")
                        .HasForeignKey("IdHd")
                        .HasConstraintName("FK_HinhThucThanhToan_HoaDon");

                    b.HasOne("F5Clothes_DAL.Models.KhachHang", "IdKhNavigation")
                        .WithMany("HinhThucThanhToans")
                        .HasForeignKey("IdKh")
                        .HasConstraintName("FK_HinhThucThanhToan_KhachHang");

                    b.HasOne("F5Clothes_DAL.Models.NhanVien", "IdNvNavigation")
                        .WithMany("HinhThucThanhToans")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK_HinhThucThanhToan_NhanVien");

                    b.Navigation("IdHdNavigation");

                    b.Navigation("IdKhNavigation");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HoaDon", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.KhachHang", "IdKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKh")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.HasOne("F5Clothes_DAL.Models.NhanVien", "IdNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.HasOne("F5Clothes_DAL.Models.VouCher", "IdVouCherNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdVouCher")
                        .HasConstraintName("FK_HoaDon_VouCher");

                    b.Navigation("IdKhNavigation");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("IdVouCherNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.HoaDon", "IdHdNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHd")
                        .HasConstraintName("FK_HoaDonChiTiet_HoaDon");

                    b.HasOne("F5Clothes_DAL.Models.SanPhamChiTiet", "IdSpctNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSpct")
                        .HasConstraintName("FK_HoaDonChiTiet_SanPhamChiTiet");

                    b.Navigation("IdHdNavigation");

                    b.Navigation("IdSpctNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.Image", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.SanPham", "IdSpNavigation")
                        .WithMany("Images")
                        .HasForeignKey("IdSp")
                        .HasConstraintName("FK_Image_SanPham");

                    b.Navigation("IdSpNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.LichSuHoaDon", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.HoaDon", "IdHdNavigation")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdHd")
                        .HasConstraintName("FK_LichSuHoaDon_HoaDon");

                    b.Navigation("IdHdNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.NhanVien", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.ChucVu", "IdCvNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCv")
                        .HasConstraintName("FK_NhanVien_ChucVu");

                    b.Navigation("IdCvNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.RefeshToken", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.NhanVien", "IdNvNavigation")
                        .WithMany("RefeshTokens")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK_RefeshToken_NhanVien");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.SanPham", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.ChatLieu", "IdClNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdCl")
                        .HasConstraintName("FK_SanPham_ChatLieu");

                    b.HasOne("F5Clothes_DAL.Models.DanhMuc", "IdDmNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDm")
                        .HasConstraintName("FK_SanPham_DanhMuc");

                    b.HasOne("F5Clothes_DAL.Models.GiamGium", "IdGgNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdGg")
                        .HasConstraintName("FK_SanPham_GiamGia");

                    b.HasOne("F5Clothes_DAL.Models.ThuongHieu", "IdThNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdTh")
                        .HasConstraintName("FK_SanPham_ThuongHieu");

                    b.HasOne("F5Clothes_DAL.Models.XuatXu", "IdXxNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdXx")
                        .HasConstraintName("FK_SanPham_XuatXu");

                    b.Navigation("IdClNavigation");

                    b.Navigation("IdDmNavigation");

                    b.Navigation("IdGgNavigation");

                    b.Navigation("IdThNavigation");

                    b.Navigation("IdXxNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("F5Clothes_DAL.Models.MauSac", "IdMsNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMs")
                        .HasConstraintName("FK_SanPhamChiTiet_MauSac");

                    b.HasOne("F5Clothes_DAL.Models.Size", "IdSizeNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSize")
                        .HasConstraintName("FK_SanPhamChiTiet_Size");

                    b.HasOne("F5Clothes_DAL.Models.SanPham", "IdSpNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSp")
                        .HasConstraintName("FK_SanPhamChiTiet_SanPham");

                    b.Navigation("IdMsNavigation");

                    b.Navigation("IdSizeNavigation");

                    b.Navigation("IdSpNavigation");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GiamGium", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HinhThucThanhToans");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHangs");

                    b.Navigation("HinhThucThanhToans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HinhThucThanhToans");

                    b.Navigation("HoaDons");

                    b.Navigation("RefeshTokens");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.SanPham", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.Size", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.VouCher", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("F5Clothes_DAL.Models.XuatXu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
